#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function parseArgs(argv) {
  const args = {};
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const key = a.slice(2);
      args[key] = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[++i] : true;
    }
  }
  return args;
}

function loadJson(filePath, fallback = {}) {
  if (!filePath || !fs.existsSync(filePath)) return fallback;
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function loadResearchNotes(dirPath) {
  if (!dirPath || !fs.existsSync(dirPath)) return [];
  const files = fs.readdirSync(dirPath).filter((f) => f.endsWith('.md'));
  return files.map((file) => ({
    file,
    content: fs.readFileSync(path.join(dirPath, file), 'utf8')
  }));
}

function renderMarkdown(profile, researchNotes) {
  const sections = [
    'household_profile',
    'location',
    'threats',
    'supplies',
    'communications',
    'evacuation',
    'shelter_in_place',
    'medical',
    'skills',
    'finances',
    'community'
  ];

  let out = '# SHTFx Handbook\n\n';
  out += '_Generated by Phase 1 markdown generator stub._\n\n';

  for (const section of sections) {
    out += `## ${section}\n\n`;
    const value = profile[section];
    if (value === undefined) {
      out += '- TODO: Add data for this section.\n\n';
    } else {
      out += '```json\n' + JSON.stringify(value, null, 2) + '\n```\n\n';
    }
  }

  out += '## Research Notes Used\n\n';
  if (!researchNotes.length) {
    out += '- None found\n';
  } else {
    for (const note of researchNotes) {
      out += `- ${note.file}\n`;
    }
  }

  out += '\n## TODO (Phase 2)\n';
  out += '- Render handbook to PDF\n';
  out += '- Render handbook to HTML\n';

  return out;
}

function main() {
  const args = parseArgs(process.argv);
  const profilePath = args.profile || 'profile.json';
  const researchPath = args.research || 'research';
  const outputPath = args.out || 'handbook.md';

  const profile = loadJson(profilePath, {});
  const notes = loadResearchNotes(researchPath);
  const markdown = renderMarkdown(profile, notes);

  fs.writeFileSync(outputPath, markdown, 'utf8');
  console.log(`Generated ${outputPath}`);
  console.log('TODO: PDF and HTML renderers are Phase 2 stubs.');
}

main();
